# Uncomment the next line to define a global platform for your project
 #source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '8.0'

 use_frameworks!

target 'swiftPM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks

  # Pods for swiftPM
  pod 'Alamofire', :git => "https://github.com/Alamofire/Alamofire.git"
  pod 'SwiftyJSON'
  pod 'Alamofire-SwiftyJSON', :git => "https://github.com/SwiftyJSON/Alamofire-SwiftyJSON.git"

  target 'swiftPMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swiftPMUITests' do
    inherit! :search_paths
    # Pods for testing
    
  end

 

end
