source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'NoteSomething' do
	pod 'SwiftyJSON',:git => "https://github.com/SwiftyJSON/SwiftyJSON.git" 
        pod 'Alamofire', :git => "https://github.com/Alamofire/Alamofire.git" 
end
