//json

var lang_data = {
	"ja":[{}],
	"en":[

		{
        "title_txt":"Survey conducted by Tokyo prefecture",
        "q1_1txt":"Where do you live?  If you live in Japan, please write your prefecture of residence.  If you live outside Japan, please write your country of residence. ",
        "q1_2txt":"Prefecture",
        "q1_3txt":"In case of Tokyo",
        "q1_4txt":"City name",
        "q1_5txt":"If outside Japan",
        "q1_6txt":"Nation",
        "q2_1txt":"Please inform us about your sex and age. ",
        "q2_2txt":"Sex",
        "q2_3txt":"Male",
        "q2_4txt":"Female",
        "q2_5txt":"Age",
        "q2_6txt":"Under 10",
        "q2_7txt":"10s",
        "q2_8txt":"20s",
        "q2_9txt":"30s",
        "q2_10txt":"40s",
        "q2_11txt":"50s",
        "q2_12txt":"60s",
        "q2_13txt":"70s",
        "q2_14txt":"80s or over",
        "q3_1txt":"Do you stay in Tokyo Waterfront City for this trip?",
        "q3_2txt":"In the case of an overnight trip, how many nights do you stay?  <span class=\"spn_ub\">How many nights</span> do you stay and <span class=\"spn_ub\">how many lodging facilities</span> do you use <span class=\"spn_ub\">in Tokyo Waterfront City</span>?  <span class=\"spn_ub\">What kind of accommodation</span> do you use <span class=\"spn_ub\">in Tokyo Water front City</span>?  ※multiple-choice",
        "q3_3txt":"No",
        "q3_4txt":"Number of lodging facilities inside Tokyo Waterfront City",
        "q3_5txt":"Overnight",
        "q3_6txt":"Number of nights",
        "q3_7txt":"nights",
        "q3_8txt":"including    nights inside Tokyo Waterfront City.",
        "q3_9txt":"nights",
        "q3_10txt":"facilities",
        "q3_11txt":"Accommodation inside Tokyo Waterfront City",
        "q3_12txt":"Parents', acquaintance's,<br> or relative's home",
        "q3_13txt":"Hotel",
        "q3_14txt":"Car (not at a campsite) or transportation facility",
        "q3_15txt":"Villa, resort condominium",
        "q3_16txt":"Member-only accommodation",
        "q3_17txt":"Other",
        "q3_18txt":"＜Name of lodging facility＞",
        "q3_19txt":"Name of lodging facility",
        "q3_20txt":"",
        "q3_21txt":"nights",
        "q4_1txt":"What is the main purpose of your trip?  <span class=\"spn_u\">※Please choose only one item.</span> ",
        "q4_2txt":"Business",
        "q4_3txt":"Tourism",
        "q4_4txt":"Returning home・Visiting Friend & Relative",
        "q4_5txt":"Shopping",
        "q4_6txt":"Event participation",
        "q4_7txt":"Viewing of theatrical/public performance, etc.; ",
        "q4_8txt":"meal",
        "q4_9txt":"Other (If not any of 1-3)",
        "q5_1txt":"How many people are you traveling with?  And who are they?  Please fill out the number of people <span class=\"spn_ub\">including yourself</span> and select the item showing who they are.  <span class=\"spn_ub\">※Please count in babies and children.</span>",
        "q5_2txt":"people",
        "q5_3txt":"For 2 or more people",
        "q5_4txt":"Family",
        "q5_5txt":"Friends",
        "q5_6txt":"Group tour of your workplace or school",
        "q5_7txt":"Other",
        "q6_1txt":"Do you know how many times have your companions visited this spot? If you know, please fill out the number of your companions <span class=\"spn_ub\">including yourself</span> in the blanks below.",
        "q6_2txt":"※The total of answers matches Q5",
        "q6_3txt":"Yes",
        "q6_4txt":"the first time",
        "q6_5txt":",",
        "q6_6txt":"the second time",
        "q6_7txt":"",
        "q6_8txt":"the third time",
        "q6_9txt":",",
        "q6_10txt":"the fourth time and more",
        "q6_11txt":"",
        "q6_12txt":"No",
        "q7_1_1txt":"What transportation did you use to come to Tokyo Warterfront City?",
        "q7_1_2txt":"Rinkai Line",
        "q7_1_3txt":"Yurikamome(Monorail)",
        "q7_1_4txt":"Tour bus",
        "q7_1_5txt":"Express bus",
        "q7_1_6txt":"Local bus service",
        "q7_1_7txt":"Free round route bus<br>(BAY SHUTTLE)",
        "q7_1_8txt":"Shuttle bus in facilities",
        "q7_1_9txt":"Water Bus",
        "q7_1_10txt":"Taxi",
        "q7_1_11txt":"Car",
        "q7_1_12txt":"Bicycle",
        "q7_1_13txt":"Rent-a-Bicycle",
        "q7_1_14txt":"Motorcycle",
        "q7_1_15txt":"Walk",
        "q7_1_16txt":"Others",
        "q7_2_1txt":"What tourist spots did you visit in the Tokyo Warterfront City? Please enter the location numbers of the places you have visited and plan to visit in chronological order. Also, please enter the transportation provider you used to go from one location to the next.",
        "q7_2_2txt":"Arrival Spot of Tokyo Warterfront City <br>(Station /Bus stop, etc.)",
        "q7_2_3txt":"Tourist Spot No.",
        "q7_2_4txt":"Here",
        "q7_2_5txt":"Departure Spot from Tokyo Warterfront City <br>(Station /Bus stop, etc.)",
        "q7_2_6txt":"Transportation mode",
        "q7_2_7txt":"1 Panasonic Cernter TOKYO",
        "q7_2_8txt":"2 TOKYO WATER SCIENCE MUSEUM",
        "q7_2_9txt":"3 Ariake Colosseum",
        "q7_2_10txt":"4 Tokyo Fashion Town (TFT Bldg)",
        "q7_2_11txt":"5 Tokyo Big Sight",
        "q7_2_12txt":"6 <span style=\"font-size: 11px;\">Tokyo Sewerage Museum \"Rainbow\"(Ariake Clean Center)</span>",
        "q7_2_13txt":"7 TOC ARIAKE",
        "q7_2_14txt":"8 DIFFER ARIAKE",
        "q7_2_15txt":"9 Tokyo Rinkai Disaster Prevention Park",
        "q7_2_16txt":"10 DiverCiry Tokyo",
        "q7_2_17txt":"11 TOKYO PORT MUSEUM(Aomi Frontier Bldg)",
        "q7_2_18txt":"12 Telecom Center Observatory",
        "q7_2_19txt":"13 palette town",
        "q7_2_20txt":"14 Oedo-Onsen Monogatari",
        "q7_2_21txt":"15 MEGAWEB",
        "q7_2_22txt":"16 Zepp　Tokyo",
        "q7_2_23txt":"17 <span style=\"font-size: 10px;\">National Museum of Emerging Science and Innobvation(Miraikan)</span>",
        "q7_2_24txt":"18 THE GUNDAM BASE TOKYO",
        "q7_2_25txt":"19 Zepp DiverCiry(DiverCiry Tokyo)",
        "q7_2_26txt":"20 Fuji Television",
        "q7_2_27txt":"21 Odaiba Marine Park",
        "q7_2_28txt":"22 JOYPOLIS(DEXKS Tokyo Beach)",
        "q7_2_29txt":"23 AQUA CITY ODAIBA",
        "q7_2_30txt":"24 Others（Please write spechific saightseeing spots）",
        "q7_2_31txt":"Tourist Spot",
        "q7_2_32txt":"No.",
        "q7_2_33txt":"Tourist spot",
        "q7_2_34txt":"Panasonic Cernter TOKYO",
        "q7_2_35txt":"TOKYO WATER SCIENCE MUSEUM",
        "q7_2_36txt":"Ariake Colosseum",
        "q7_2_37txt":"Tokyo Fashion Town (TFT Bldg)",
        "q7_2_38txt":"Tokyo Big Sight",
        "q7_2_39txt":"<span style=\"font-size: 11px;\">Tokyo Sewerage Museum \"Rainbow\"(Ariake Clean Center)</span>",
        "q7_2_40txt":"TOC ARIAKE",
        "q7_2_41txt":"DIFFER ARIAKE",
        "q7_2_42txt":"Tokyo Rinkai Disaster Prevention Park",
        "q7_2_43txt":"DiverCiry Tokyo",
        "q7_2_44txt":"TOKYO PORT MUSEUM(Aomi Frontier Bldg)",
        "q7_2_45txt":"Telecom Center Observatory",
        "q7_2_46txt":"palette town",
        "q7_2_47txt":"Oedo-Onsen Monogatari",
        "q7_2_48txt":"MEGAWEB",
        "q7_2_49txt":"No.",
        "q7_2_50txt":"Tourist spot",
        "q7_2_51txt":"Zepp　Tokyo",
        "q7_2_52txt":"<span style=\"font-size: 10px;\">National Museum of Emerging Science and Innobvation(Miraikan)</span>",
        "q7_2_53txt":"THE GUNDAM BASE TOKYO",
        "q7_2_54txt":"Zepp DiverCiry(DiverCiry Tokyo)",
        "q7_2_55txt":"Fuji Television",
        "q7_2_56txt":"Odaiba Marine Park",
        "q7_2_57txt":"JOYPOLIS(DEXKS Tokyo Beach)",
        "q7_2_58txt":"AQUA CITY ODAIBA",
        "q7_2_59txt":"Others（Please write spechific saightseeing spots）",
        "q7_2_60txt":"Transportation facilities",
        "q7_2_61txt":"① Rinkai Line",
        "q7_2_62txt":"② Yurikamome(Monorail)",
        "q7_2_63txt":"③ Tour bus",
        "q7_2_64txt":"④ Express bus",
        "q7_2_65txt":"⑤ Local bus service",
        "q7_2_66txt":"⑥ Free round route bus(BAY SHUTTLE)",
        "q7_2_67txt":"⑦ Shuttle bus in facilities",
        "q7_2_68txt":"⑧ Water Bus",
        "q7_2_69txt":"⑨ Taxi",
        "q7_2_70txt":"⑩ Car",
        "q7_2_71txt":"⑪ Bicycle",
        "q7_2_72txt":"⑫ Rent-a-Bicycle",
        "q7_2_73txt":"⑬ Motorcycle",
        "q7_2_74txt":"⑭ Walk",
        "q7_2_75txt":"⑮ Others",
        "q8_1txt":"Was this visit part of a travel package?",
        "q8_2txt":"Yes",
        "q8_3txt":"No",
        "q9_1txt":"How did you obtain information for this trip to Tokyo Water Front City? Choose all that apply and circle the number/s.",
        "q9_2txt":"Guidebooks",
        "q9_3txt":"Travel magazines",
        "q9_4txt":"Pamphlets",
        "q9_5txt":"Newspapers and/or magazines",
        "q9_6txt":"TV and/or radio",
        "q9_7txt":"From family members and/or friends",
        "q9_8txt":"Travel agency",
        "q9_9txt":"Tourist information office",
        "q9_10txt":"Website (via personal computer)",
        "q9_11txt":"Website (via cellular phone)",
        "q9_12txt":"ＳＮＳ（Facebook / Twitter / Instagram / Renren, etc.）",
        "q9_13txt":"Others (Please specify)",
        "q10_1txt":"What elements do you think would make Tokyo Waterfront City a more attractive town than it is at present?<span class=\"spn_u\">*Multiple answers allowed</span>",
        "q10_2txt":"[Townscape]",
        "q10_3txt":"Enjoying natural scenery",
        "q10_4txt":"Enjoying a modern townscape",
        "q10_5txt":"Enjoying a fashionable townscape",
        "q10_6txt":"[Facilities]",
        "q10_7txt":"Commercial facilities",
        "q10_8txt":"Recreational facilities (amusement park, etc.)",
        "q10_9txt":"Learning facilities (science museum, etc.)",
        "q10_10txt":"Arts facilities (art museum, etc.)",
        "q10_11txt":"Accommodation facilities (high-end hotel, etc.)",
        "q10_12txt":"Dining facilities",
        "q10_13txt":"Facilities for interactive or experience-based tourism (kimono dress-up   experience, etc.)",
        "q10_14txt":"Sports facilities",
        "q10_15txt":"Decorative illumination displays",
        "q10_16txt":"Waterside spots",
        "q10_17txt":"Events",
        "q10_18txt":"Observatory",
        "q10_2_1txt":"With regards to the items you selected above among the facilities, etc. please specify below if there is any particular kind of element, characteristic, etc. you think would make Tokyo Waterfront City a more attractive town.",
        "q10_2_2txt":"(Answer here as you please)",
        "q11_1txt":"How satisfied are you with your current visit to Tokyo Waterfront City (Around Here) ? <span class=\"spn_u\">※Please choose only one item.</span>",
        "q11_2txt":"Very satisfied",
        "q11_3txt":"Satisfied",
        "q11_4txt":"Slightly satisfied",
        "q11_5txt":"Neutral",
        "q11_6txt":"Slightly dissatisfied",
        "q11_7txt":"Dissatisfied",
        "q11_8txt":"Very dissatisfied",
        "q12_1txt":"Would you like to come to Tokyo Waterfront City (Around Here)  again? <span class=\"spn_u\">※Please choose only one item.</span>",
        "q12_2txt":"Definitely",
        "q12_3txt":"Yes",
        "q12_4txt":"Probably",
        "q12_5txt":"Not sure",
        "q12_6txt":"Not really",
        "q12_7txt":"No",
        "q12_8txt":"Definitely not",
        "q13_1txt":"During your visit to the Tokyo Warterfront City, did anything dissatisfy you? Was there anything you feel could be improved?",
        "q13_2txt":"I can’t relax and enjoy shopping because of the crowds",
        "q13_3txt":"Transportation links from spot to spot are inconvenient",
        "q13_4txt":"There aren’t enough information signs for tourists, making it hard to find locations",
        "q13_5txt":"There aren’t enough foreign-language tourist information and signs",
        "q13_6txt":"It’s difficult to communicate in languages other than Japanese",
        "q13_7txt":"Costs to use and enter facilities are high",
        "q13_8txt":"Prices overall are high",
        "q13_9txt":"I can’t relax and enjoy my meals because restaurants and other dining facilities are  too crowded",
        "q13_10txt":"Accessibility of Wi-Fi",
        "q13_11txt":"There aren’t enough rest areas",
        "q13_12txt":"It’s difficult to get local information",
        "q13_13txt":"I do not feel safe",
        "q13_14txt":"None in particular",
        "q13_15txt":"Other (Please feel free to enter any additional comments or observations you may have in the space below.)",
        "end_txt":"Thank you very much for your cooperation."
		}

	],
	"ko":[

		{
		"title_txt":"동경도가 실시하는 조사",
        "q1_1txt":"댁은 어디십니까? 일본에 계시면 都道府県명을, 해외에 계시면 국가를 쓰십시오.",
        "q1_2txt":"都道府県명",
        "q1_3txt":"동경도 라면",
        "q1_4txt":"区市町村명",
        "q1_5txt":"해외이라면",
        "q1_6txt":"국가",
        "q2_1txt":"성별과 연령의 해당부분을 동그라미로 두르십시오. <span class=\"spn_u\">※각각 하나씩.</span>",
        "q2_2txt":"성별",
        "q2_3txt":"남성",
        "q2_4txt":"여성",
        "q2_5txt":"연령",
        "q2_6txt":"10 세 미만",
        "q2_7txt":"10 대",
        "q2_8txt":"20 대",
        "q2_9txt":"30 대",
        "q2_10txt":"40 대",
        "q2_11txt":"50 대",
        "q2_12txt":"60 대",
        "q2_13txt":"70 대",
        "q2_14txt":"80 세 이상",
        "q3_1txt":"이번 여행에서는 임해부도심내(이지역내)에 숙박하십니까? <span class=\"spn_u\">※하나만 동그라미로 두르십시오</span>",
        "q3_2txt":"숙박하시는 경우、<span class=\"spn_ub\">이번여행의 총숙박수</span>를 기입해주시고, <span class=\"spn_ub\">그중 임해부도심 지역내에서 몇박하는지, 몇 시설에서 숙박하는지를</span> 기입해주십시오. <span class=\"spn_u\">※몇개도.</span>",
        "q3_3txt":"이지역내에 숙박하지 않는다",
        "q3_4txt":"에리어내 에서 숙박한 시설수",
        "q3_5txt":"숙박한다（숙박했다）",
        "q3_6txt":"총 숙박수",
        "q3_7txt":"박",
        "q3_8txt":"그중 임해부도심내",
        "q3_9txt":"박",
        "q3_10txt":"시설",
        "q3_11txt":"＜지역내 숙박시설＞",
        "q3_12txt":"실가와 친구・친척댁",
        "q3_13txt":"호텔",
        "q3_14txt":"（캠프이외의）차내 숙박・교통기관내에서의 숙박",
        "q3_15txt":"별장・리조트형 아파트",
        "q3_16txt":"회원제 숙박시설",
        "q3_17txt":"기타",
        "q3_18txt":"＜지역내 숙박시설명＞",
        "q3_19txt":"숙박시설명",
        "q3_20txt":"숙박수",
        "q3_21txt":"박",
        "q4_1txt":"이번 여행의 주요 목적은 무엇입니까? <span class=\"spn_u\">※하나만 선택.</span>",
        "q4_2txt":"비지네스",
        "q4_3txt":"관광",
        "q4_4txt":"귀성・지인방문",
        "q4_5txt":"쇼핑",
        "q4_6txt":"이벤트 참가",
        "q4_7txt":"연극・공연등의 감상",
        "q4_8txt":"식사",
        "q4_9txt":"그 외",
        "q5_1txt":"누구와 함께, 몇분이 함께하시는 여행하십니까? <span class=\"spn_u\">※유아와 어린 아이도 포함</span>",
        "q5_2txt":"명（귀하를 포함）",
        "q5_3txt":"２명 이상인 경우",
        "q5_4txt":"가족",
        "q5_5txt":"친구",
        "q5_6txt":"직장・학교등의 단체여행",
        "q5_7txt":"기타",
        "q6_1txt":"임해부도심 (이지역)에는 몇번째 방문이십니까?",
        "q6_2txt":"※회답 인원수 합계는 Q5 와 일치함.",
        "q6_3txt":"알고있음",
        "q6_4txt":"1 번째 방문 인원수",
        "q6_5txt":"명,",
        "q6_6txt":"2 번째 방문 인원수",
        "q6_7txt":"명",
        "q6_8txt":"3 번째 방문 인원수",
        "q6_9txt":"명,",
        "q6_10txt":"4 번째 방문 인원수",
        "q6_11txt":"명",
        "q6_12txt":"모름",
        "q7_1_1txt":"이번, 임해부도심내(이지역내) 에는 어떤 교통기관으로 들어오셨습니까?",
        "q7_1_2txt":"린카이선",
        "q7_1_3txt":"유리카모메",
        "q7_1_4txt":"전세버스・관광버스",
        "q7_1_5txt":"고속버스",
        "q7_1_6txt":"합승버스",
        "q7_1_7txt":"무료 순회 버스 BAY SHUTTLE",
        "q7_1_8txt":"시설의 환송버스",
        "q7_1_9txt":"수상버스",
        "q7_1_10txt":"택시・하이어",
        "q7_1_11txt":"승용차",
        "q7_1_12txt":"자전거",
        "q7_1_13txt":"렌터 사이클",
        "q7_1_14txt":"오토바이",
        "q7_1_15txt":"도보",
        "q7_1_16txt":"그 외",
        "q7_2_1txt":"이번의 임해부도심(이지역내)으로의 여행에서 어디를 관광하셨습니까? 앞으로의 예정을 포함해, 관광지의 번호를 방문한 (방문예정) 순번으로 기입해주십시오. 그리고, 이동에 이용한 교통기관도 기입해주십시오.",
        "q7_2_2txt":"임해부도심내 도착지<br>(역, 버스 정류장 등)",
        "q7_2_3txt":"관광지 번호",
        "q7_2_4txt":"조사지점",
        "q7_2_5txt":"임해부도심외로의 출발지<br>(역,버스 정류장 등)",
        "q7_2_6txt":"교통 기관",
        "q7_2_7txt":"1 파나소닉 센터 도쿄",
        "q7_2_8txt":"2 동경도 물의 과학관",
        "q7_2_9txt":"3 아리아케 코로시움",
        "q7_2_10txt":"4 도쿄 패션타운 원더 아리아케 베이 몰",
        "q7_2_11txt":"5 도쿄 빅사이트",
        "q7_2_12txt":"6 동경도 무지개의 하수도관",
        "q7_2_13txt":"7 ＴＯＣ아리아케",
        "q7_2_14txt":"8 디화 아리아케",
        "q7_2_15txt":"9 동경 임해광역 방재 공원・소나에리아 도쿄",
        "q7_2_16txt":"10 다이버 시티 도쿄 플라자",
        "q7_2_17txt":"11 도쿄 미나토 관",
        "q7_2_18txt":"12 텔레컴 센터 전망대",
        "q7_2_19txt":"13 팔레트 타운",
        "q7_2_20txt":"14 오에도 온천 모노가타리",
        "q7_2_21txt":"15 메가 웹",
        "q7_2_22txt":"16 Zepp　Tokyo",
        "q7_2_23txt":"17 일본과학 미래관",
        "q7_2_24txt":"18 THE GUNDAM BASE TOKYO",
        "q7_2_25txt":"19 Zepp　다이바 시티",
        "q7_2_26txt":"20 후지 텔레비 본사 빌딩",
        "q7_2_27txt":"21 도립 오다이바 해병 공원",
        "q7_2_28txt":"22 도쿄 조이포리스",
        "q7_2_29txt":"23 아쿠아시티 오다이바",
        "q7_2_30txt":"24 그 외 （구체적으로 스포트명을 적어 주세요.）",
        "q7_2_31txt":"【표】관광 스포트",
        "q7_2_32txt":"번호",
        "q7_2_33txt":"방문지점",
        "q7_2_34txt":"파나소닉 센터 도쿄",
        "q7_2_35txt":"동경도 물의 과학관",
        "q7_2_36txt":"아리아케 코로시움",
        "q7_2_37txt":"도쿄 패션타운 원더 아리아케 베이 몰",
        "q7_2_38txt":"도쿄 빅사이트",
        "q7_2_39txt":"동경도 무지개의 하수도관",
        "q7_2_40txt":"ＴＯＣ아리아케",
        "q7_2_41txt":"디화 아리아케",
        "q7_2_42txt":"동경 임해광역 방재 공원・소나에리아 도쿄",
        "q7_2_43txt":"다이버 시티 도쿄 플라자",
        "q7_2_44txt":"도쿄 미나토 관",
        "q7_2_45txt":"텔레컴 센터 전망대",
        "q7_2_46txt":"팔레트 타운",
        "q7_2_47txt":"오에도 온천 모노가타리",
        "q7_2_48txt":"메가 웹",
        "q7_2_49txt":"번호",
        "q7_2_50txt":"방문지점",
        "q7_2_51txt":"Zepp　Tokyo",
        "q7_2_52txt":"일본과학 미래관",
        "q7_2_53txt":"THE GUNDAM BASE TOKYO",
        "q7_2_54txt":"Zepp　다이바 시티",
        "q7_2_55txt":"후지 텔레비 본사 빌딩",
        "q7_2_56txt":"도립 오다이바 해병 공원",
        "q7_2_57txt":"도쿄 조이포리스",
        "q7_2_58txt":"아쿠아시티 오다이바",
        "q7_2_59txt":"그 외 （구체적으로 스포트명을 적어 주세요.）",
        "q7_2_60txt":"【표】교통기관",
        "q7_2_61txt":"① 린카이선",
        "q7_2_62txt":"② 유리카모메",
        "q7_2_63txt":"③ 전세버스・관광버스",
        "q7_2_64txt":"④ 고속버스",
        "q7_2_65txt":"⑤ 합승버스",
        "q7_2_66txt":"⑥ 무료 순회 버스 BAY SHUTTLE",
        "q7_2_67txt":"⑦ 시설의 환송버스",
        "q7_2_68txt":"⑧ 수상버스",
        "q7_2_69txt":"⑨ 택시・하이어",
        "q7_2_70txt":"⑩ 승용차",
        "q7_2_71txt":"⑪ 자전거",
        "q7_2_72txt":"⑫ 렌터 사이클",
        "q7_2_73txt":"⑬ 오토바이",
        "q7_2_74txt":"⑭ 도보",
        "q7_2_75txt":"⑮ 그 외",
        "q8_1txt":"이번 임해부도심(이지역)으로의 여행은 패키지 상품에 포함되어 있습니까?<span class=\"spn_u\">※ 하나만 선택</span>",
        "q8_2txt":"포함되어 있음",
        "q8_3txt":"포함되어 있지 않음",
        "q9_1txt":"이번 여행에 있어서, 임해부도심(이지역내)의 정보를 어디서 입수하셨습니까? <span class=\"spn_u\">※복수 선택</span>",
        "q9_2txt":"가이드 북",
        "q9_3txt":"여행 전문 잡지",
        "q9_4txt":"팜플렛",
        "q9_5txt":"신문·잡지",
        "q9_6txt":"텔레비젼·라디오",
        "q9_7txt":"가족·친구의 이야기",
        "q9_8txt":"여행 회사",
        "q9_9txt":"관광 안내소",
        "q9_10txt":"인터넷(PC 를 경유)",
        "q9_11txt":"인터넷(휴대전화로부터)",
        "q9_12txt":"ＳＮＳ（Facebook / Twitter / Instagram / 런런왕 등）",
        "q9_13txt":"기타",
        "q10_1txt":"귀하는 임해부도심 (이지역)에 무엇이 있으면 보다 매력적인 지역이 된다고 생각하십니까?<span class=\"spn_u\">※복수 선택</span>",
        "q10_2txt":"【거리】",
        "q10_3txt":"자연의 풍경을 즐긴다",
        "q10_4txt":"근대적인 거리를 즐긴다",
        "q10_5txt":"멋있고 세련된 거리를 즐긴다",
        "q10_6txt":"【시설 등】",
        "q10_7txt":"상업시설",
        "q10_8txt":"오락시설（유원지 등）",
        "q10_9txt":"학습시설設（과학관 등）",
        "q10_10txt":"예술시설（미술관 등）",
        "q10_11txt":"숙박시설（고급 호텔 등）",
        "q10_12txt":"음식시설",
        "q10_13txt":"체험형 관광시설（키모노 체험 등）",
        "q10_14txt":"스포츠 시설",
        "q10_15txt":"일루미네이션",
        "q10_16txt":"친수 공간",
        "q10_17txt":"이벤트",
        "q10_18txt":"전망대",
        "q10_2_1txt":"시설 등에서 선택하신 항목에 있어서, 구체적으로 어떤것이 있으면, 임해부도심 (이지역)이 더욱 매력적인 지역이 된다고 생각하십니까? 구체적으로 기입해 주십시오.",
        "q10_2_2txt":"",
        "q11_1txt":"이번 임해부도심(이지역)으로의 여행있어서、어느정도 만족하십니까? <span class=\"spn_u\">※ 하나만 선택</span>",
        "q11_2txt":"매우만족",
        "q11_3txt":"만족",
        "q11_4txt":"약간만족",
        "q11_5txt":"보통",
        "q11_6txt":"약간불만",
        "q11_7txt":"불만",
        "q11_8txt":"매우불만",
        "q12_1txt":"임해부도심(이지역)에 다시 오고싶다고 생각하십니까? <span class=\"spn_u\">※하나만 선택</span>",
        "q12_2txt":"꼭 오고싶다",
        "q12_3txt":"오고싶다",
        "q12_4txt":"약간 오고싶다",
        "q12_5txt":"그저그렇다",
        "q12_6txt":"별로 오고싶지 않다",
        "q12_7txt":"오고싶지 않다",
        "q12_8txt":"절대 오고싶지 않다",
        "q13_1txt":"임해부도심(이지역)에 방문하셔서, 뭔가 불편함을 느낀점이나 개선 했으면 좋겠다고 느끼신점이 있습니까? <span class=\"spn_u\">※복수 선택</span>",
        "q13_2txt":"혼잡해서, 천천히 쇼핑을 즐길수 없다",
        "q13_3txt":"각 스포트로의 교통편이 나쁘다",
        "q13_4txt":"안내표식이 충분하지 않고, 각 스포트를 찾기가 힘들다",
        "q13_5txt":"외국어로의 안내와 간판이 충분하지 않다",
        "q13_6txt":"외국어로 의사소통이 힘들다",
        "q13_7txt":"시설이용료나 입관료등이 비싸다",
        "q13_8txt":"전반적으로 물가가 비싸다",
        "q13_9txt":"레스토랑등의 식사시설이 혼잡해서, 식사를 천천히 즐길수 없다",
        "q13_10txt":"Wi-Fi 를 사용할 수 있는 장소가 적다",
        "q13_11txt":"휴식할수 있는 장소가 적다",
        "q13_12txt":"주변정보를 취득하기가 어렵다",
        "q13_13txt":"치안상태에 불안함을 느낀다",
        "q13_14txt":"특별히 없음",
        "q13_15txt":"그 외（그 외 느낀신점이 있으시면, 뭐든지 괜찮습니다. 아래의 공란에 적어주십시오.）",
        "end_txt":"조사내용은 이상입니다. 감사합니다."
		}

	],
	"ch_t":[

		{
		"title_txt":"東京都問卷調查",
        "q1_1txt":"請問您居住在什麼地方？日本國內的遊客請填寫您所在的都道府縣名，國外的遊客請填寫您的國家。另外，本次調查區域內的當地遊客請填寫您居住的區市町村名。",
        "q1_2txt":"都道府縣名",
        "q1_3txt":"本地遊客",
        "q1_4txt":"區市町村名",
        "q1_5txt":"外國遊客",
        "q1_6txt":"國家",
        "q2_1txt":"請選擇您的年齡和性別。<span class=\"spn_u\">※年齡，性別均為單選</span>",
        "q2_2txt":"性別",
        "q2_3txt":"男性",
        "q2_4txt":"女性",
        "q2_5txt":"年齡",
        "q2_6txt":"10歲以下",
        "q2_7txt":"10歲~19歲",
        "q2_8txt":"20歲~29歲",
        "q2_9txt":"30歲~39歲",
        "q2_10txt":"40歲~49歲",
        "q2_11txt":"50歲~59歲",
        "q2_12txt":"60歲~69歲",
        "q2_13txt":"70歲~79歲",
        "q2_14txt":"80歲以上",
        "q3_1txt":"此次前來臨海副都心旅行，行程可有規劃在臨海副都心住宿呢？※請圈選一個選項",
        "q3_2txt":"若有規劃在臨海副都心住宿，<span class=\"spn_ub\">請填寫此次旅行總計住宿幾晚</span>，<span class=\"spn_ub\">其中在臨海副都心內住宿幾晚</span>，<span class=\"spn_ub\">住宿設施共幾處</span>，<span class=\"spn_ub\">以及臨海副都心內住宿設施之類型。</span>※可圈選多個選項",
        "q3_3txt":"未規劃在臨海副都心內住宿",
        "q3_4txt":"臨海副都心內留宿場所總計",
        "q3_5txt":"有規劃(或已經)在臨海副都心內住宿",
        "q3_6txt":"留宿",
        "q3_7txt":"晚",
        "q3_8txt":"其中在臨海副都心內",
        "q3_9txt":"晚",
        "q3_10txt":"處",
        "q3_11txt":"＜在臨海副都心內使用的留宿場所＞",
        "q3_12txt":"老家或親朋好友家",
        "q3_13txt":"飯店",
        "q3_14txt":"（野營地之外）車輛等交通工具內",
        "q3_15txt":"別墅・度假公寓",
        "q3_16txt":"會員制的住宿設施",
        "q3_17txt":"其他",
        "q3_18txt":"＜臨海副都心內投宿設施名＞",
        "q3_19txt":"投宿設施名",
        "q3_20txt":"投宿數",
        "q3_21txt":"泊",
        "q4_1txt":"請問您本次旅行的目的是?(單選)",
        "q4_2txt":"商務",
        "q4_3txt":"觀光",
        "q4_4txt":"探親・訪友",
        "q4_5txt":"購物",
        "q4_6txt":"參加活動",
        "q4_7txt":"欣賞戲劇・公演等",
        "q4_8txt":"餐飲",
        "q4_9txt":"其他",
        "q5_1txt":"包括您在內，請問本次旅行您和誰同行，共計幾位遊客? ※包括孩童和嬰兒",
        "q5_2txt":"人(包括回答者)",
        "q5_3txt":"２人以上",
        "q5_4txt":"家人",
        "q5_5txt":"朋友",
        "q5_6txt":"公司、學校的集體旅行",
        "q5_7txt":"其他",
        "q6_1txt":"請問您是否了解本次旅遊團全體成員(包括您)是第幾次造訪臨海副都心呢？",
        "q6_2txt":"※總人數應與Q5一致",
        "q6_3txt":"了解",
        "q6_4txt":"<span class=\"spn_ch_t_fs\">第一次造訪此地的人數</span>",
        "q6_5txt":"<span class=\"spn_ch_t_fs\">人、</span>",
        "q6_6txt":"<span class=\"spn_ch_t_fs\">第二次造訪此地的人數</span>",
        "q6_7txt":"<span class=\"spn_ch_t_fs\">人</span>",
        "q6_8txt":"<span class=\"spn_ch_t_fs\">第三次造訪此地的人數</span>",
        "q6_9txt":"<span class=\"spn_ch_t_fs\">人、</span>",
        "q6_10txt":"<span class=\"spn_ch_t_fs\">第四次以上造訪此地的人數</span>",
        "q6_11txt":"<span class=\"spn_ch_t_fs\">人</span>",
        "q6_12txt":"不了解",
        "q7_1_1txt":"請問這次是利用什麼交通工具來到臨海副都心內？",
        "q7_1_2txt":"臨海線",
        "q7_1_3txt":"輕軌(百合海鷗號)",
        "q7_1_4txt":"遊覽車・觀光巴士",
        "q7_1_5txt":"高速巴士",
        "q7_1_6txt":"公共巴士",
        "q7_1_7txt":"免費巡迴巴士BAY SHUTTLE",
        "q7_1_8txt":"設施的接送巴士",
        "q7_1_9txt":"水上巴士",
        "q7_1_10txt":"計程車",
        "q7_1_11txt":"自駕車",
        "q7_1_12txt":"單車",
        "q7_1_13txt":"租賃單車",
        "q7_1_14txt":"摩托車",
        "q7_1_15txt":"徒步",
        "q7_1_16txt":"其他",
        "q7_2_1txt":"請問此次旅行您有造訪臨海副都心的哪些景點呢？包括您接下來準備前往的景點，請按照時間順序填寫對應的景點編號。同時也請填寫使用的交通工具。",
        "q7_2_2txt":"到臨海副都心內來的到達點<br>(車站、站牌等)",
        "q7_2_3txt":"觀光景點編號",
        "q7_2_4txt":"調查地點",
        "q7_2_5txt":"離開臨海副都心時的出發點<br>(車站、站牌等)",
        "q7_2_6txt":"交通工具",
        "q7_2_7txt":"1 東京松下中心",
        "q7_2_8txt":"2 東京都水之科學館",
        "q7_2_9txt":"3 有明競技場",
        "q7_2_10txt":"4 東京時尚城 WANZA有明灣購物中心",
        "q7_2_11txt":"5 東京國際展示場",
        "q7_2_12txt":"6 東京都彩虹下水道博物館",
        "q7_2_13txt":"7 TOC有明",
        "q7_2_14txt":"8 Differ有明",
        "q7_2_15txt":"9 東京臨海廣域防災公園",
        "q7_2_16txt":"10 DiverCity東京購物中心",
        "q7_2_17txt":"11 東京港館",
        "q7_2_18txt":"12 電信中心展望台",
        "q7_2_19txt":"13 調色板城",
        "q7_2_20txt":"14 大江戶溫泉物語",
        "q7_2_21txt":"15 MEGAWEB汽車主題樂園",
        "q7_2_22txt":"16 Zepp東京",
        "q7_2_23txt":"17 日本科學未來館",
        "q7_2_24txt":"18 THE GUNDAM BASE TOKYO",
        "q7_2_25txt":"19 Zepp DiverCity",
        "q7_2_26txt":"20 富士電視台本社大樓",
        "q7_2_27txt":"21 台場海濱公園",
        "q7_2_28txt":"22 東京JOYPOLIS",
        "q7_2_29txt":"23 AQUA CITY台場",
        "q7_2_30txt":"24 其他(請填寫具體景點名稱。)",
        "q7_2_31txt":"【附表】觀光景點",
        "q7_2_32txt":"編號",
        "q7_2_33txt":"景點",
        "q7_2_34txt":"東京松下中心",
        "q7_2_35txt":"東京都水之科學館",
        "q7_2_36txt":"有明競技場",
        "q7_2_37txt":"東京時尚城 WANZA有明灣購物中心",
        "q7_2_38txt":"東京國際展示場",
        "q7_2_39txt":"東京都彩虹下水道博物館",
        "q7_2_40txt":"TOC有明",
        "q7_2_41txt":"Differ有明",
        "q7_2_42txt":"東京臨海廣域防災公園",
        "q7_2_43txt":"DiverCity東京購物中心",
        "q7_2_44txt":"東京港館",
        "q7_2_45txt":"電信中心展望台",
        "q7_2_46txt":"調色板城",
        "q7_2_47txt":"大江戶溫泉物語",
        "q7_2_48txt":"MEGAWEB汽車主題樂園",
        "q7_2_49txt":"編號",
        "q7_2_50txt":"景點",
        "q7_2_51txt":"Zepp東京",
        "q7_2_52txt":"日本科學未來館",
        "q7_2_53txt":"THE GUNDAM BASE TOKYO",
        "q7_2_54txt":"Zepp DiverCity",
        "q7_2_55txt":"富士電視台本社大樓",
        "q7_2_56txt":"台場海濱公園",
        "q7_2_57txt":"東京JOYPOLIS",
        "q7_2_58txt":"AQUA CITY台場",
        "q7_2_59txt":"其他(請填寫具體景點名稱。)",
        "q7_2_60txt":"【附表】交通工具",
        "q7_2_61txt":"① 臨海線",
        "q7_2_62txt":"② 輕軌(百合海鷗號)",
        "q7_2_63txt":"③ 遊覽車・觀光巴士",
        "q7_2_64txt":"④ 高速巴士",
        "q7_2_65txt":"⑤ 公共巴士",
        "q7_2_66txt":"⑥ 免費巡迴巴士BAY SHUTTLE",
        "q7_2_67txt":"⑦ 設施的接送巴士",
        "q7_2_68txt":"⑧ 水上巴士",
        "q7_2_69txt":"⑨ 計程車",
        "q7_2_70txt":"⑩ 自駕車",
        "q7_2_71txt":"⑪ 單車",
        "q7_2_72txt":"⑫ 租賃單車",
        "q7_2_73txt":"⑬ 摩托車",
        "q7_2_74txt":"⑭ 徒步",
        "q7_2_75txt":"⑮ 其他",
        "q8_1txt":"請問此次造訪臨海副都心是否有包含在您參加的旅遊團行程當中呢？",
        "q8_2txt":"有包含在旅遊團行程中",
        "q8_3txt":"沒有包含在旅遊團行程中　",
        "q9_1txt":"請問您此次旅行中臨海副都心的情報是在哪裡獲得。（可複數圈選）",
        "q9_2txt":"旅遊指南",
        "q9_3txt":"旅遊專門雜誌",
        "q9_4txt":"宣傳小冊子",
        "q9_5txt":"報紙・雜誌",
        "q9_6txt":"電視節目・廣播",
        "q9_7txt":"家人・朋友的介紹",
        "q9_8txt":"旅行社",
        "q9_9txt":"觀光服務處",
        "q9_10txt":"網路(電腦)",
        "q9_11txt":"網路(智慧型手機・行動電話)",
        "q9_12txt":"ＳＮＳ（Facebook / Twitter / Instagram /人人網等）",
        "q9_13txt":"其他",
        "q10_1txt":"請問您臨海副都心若有下面何種設施等，會讓您覺得更有吸引力呢？<span class=\"spn_u\">※可複選</span>",
        "q10_2txt":"【街景】",
        "q10_3txt":"欣賞自然風景",
        "q10_4txt":"欣賞現代化街道",
        "q10_5txt":"逛時尚街區",
        "q10_6txt":"【設施等】",
        "q10_7txt":"商業設施",
        "q10_8txt":"娛樂設施（遊樂園等）",
        "q10_9txt":"學習設施（科學館等）",
        "q10_10txt":"藝術設施（美術館等）",
        "q10_11txt":"住宿設施（高級飯店等）",
        "q10_12txt":"餐飲設施",
        "q10_13txt":"體驗型旅遊設施（試穿和服等）",
        "q10_14txt":"運動設施",
        "q10_15txt":"燈飾活動",
        "q10_16txt":"水上活動景點",
        "q10_17txt":"文化娛樂活動",
        "q10_18txt":"眺望台",
        "q10_2_1txt":"關於您在“設施等”中圈選的選項，請問您認為具體有何內容會讓臨海副都心變得更有吸引力呢？　請您具體填寫",
        "q10_2_2txt":"",
        "q11_1txt":"請給出您對本次臨海副都心之行的總體滿意度。（只能圈選一項）",
        "q11_2txt":"非常滿意",
        "q11_3txt":"滿意",
        "q11_4txt":"尚可",
        "q11_5txt":"普通",
        "q11_6txt":"有點不滿意",
        "q11_7txt":"不滿意",
        "q11_8txt":"非常不滿意",
        "q12_1txt":"您今後還想再來臨海副都心旅行嗎？（只能圈選一項）",
        "q12_2txt":"一定來",
        "q12_3txt":"想來",
        "q12_4txt":"有點想來",
        "q12_5txt":"不一定",
        "q12_6txt":"不太想來",
        "q12_7txt":"不想來",
        "q12_8txt":"絕不想來",
        "q13_1txt":"此次造訪臨海副都心，您是否有感到不夠滿意或希望改善的地方呢？※（可複數圈選）",
        "q13_2txt":"太擁擠，無法好好地購物。",
        "q13_3txt":"前往各目的地的交通非常不便。",
        "q13_4txt":"導覽標誌不夠具體，難以找到目的地。",
        "q13_5txt":"外語﹝多國語言﹞導覽資料、標誌牌不夠。",
        "q13_6txt":"外語﹝多國語言﹞溝通困難。",
        "q13_7txt":"設施使用費用及門票等較貴。",
        "q13_8txt":"總體上物價比較貴。",
        "q13_9txt":"餐廳等餐飲設施很擁擠，無法好好地享用餐點。",
        "q13_10txt":"能使用Wi-Fi的地方很少。",
        "q13_11txt":"可供休息的場所太少。",
        "q13_12txt":"不易獲取鄰近地區資訊。",
        "q13_13txt":"對治安狀況感到不安。",
        "q13_14txt":"沒有",
        "q13_15txt":"其他﹝若有其他令您感到在意的地方，任何內容皆可，請填寫於以下空白處。﹞",
        "end_txt":"本次問卷調查結束。非常感謝您的合作。"
		}

	],
	"ch_s":[

		{
        "title_txt":"东京都问卷调查",
        "q1_1txt":"请问您住在什么地方？日本国内的游客请填写您所在的都道府县名，国外的旅客请填写您的国家。另外，本次调查区域内的当地游客请填写您居住的区市町村名。",
        "q1_2txt":"都道府县名",
        "q1_3txt":"本地的游客",
        "q1_4txt":"区市町村名",
        "q1_5txt":"国外的游客",
        "q1_6txt":"国家",
        "q2_1txt":"请选择您的年龄和性别。<span class=\"spn_u\">※年龄，性别均为单选</span>",
        "q2_2txt":"性别",
        "q2_3txt":"男性",
        "q2_4txt":"女性",
        "q2_5txt":"年龄",
        "q2_6txt":"10岁以下",
        "q2_7txt":"10岁~19岁",
        "q2_8txt":"20岁~29岁",
        "q2_9txt":"30岁~39岁",
        "q2_10txt":"40岁~49岁",
        "q2_11txt":"50岁~59岁",
        "q2_12txt":"60岁~69岁",
        "q2_13txt":"70岁~79岁",
        "q2_14txt":"80岁以上",
        "q3_1txt":"请问这次来临海副都心旅游，有计划在临海副都心内住宿吗？※限单选",
        "q3_2txt":"如果有计划在临海副都心内住宿，<span class=\"spn_ub\">请填写这次旅游共计住宿几晚</span>，<span class=\"spn_ub\">其中临海副都心内住宿几晚</span>，<span class=\"spn_ub\">入住的住宿设施共几处以及入住的住宿设施类型</span>。※可多选",
        "q3_3txt":"没有计划在临海副都心内住宿",
        "q3_4txt":"临海副都心内留宿场所总计",
        "q3_5txt":"有计划（或已经）在临海副都心内住宿",
        "q3_6txt":"留宿",
        "q3_7txt":"晚",
        "q3_8txt":"其中在临海副都心内",
        "q3_9txt":"晚",
        "q3_10txt":"处",
        "q3_11txt":"＜临海副都心内使用的留宿场所＞",
        "q3_12txt":"老家或亲朋好友家",
        "q3_13txt":"宾馆",
        "q3_14txt":"（野营地之外）车辆等交通工具内",
        "q3_15txt":"别墅·度假公寓",
        "q3_16txt":"会员制的住宿设施",
        "q3_17txt":"其他",
        "q3_18txt":"＜临海副都心内投宿设施名＞",
        "q3_19txt":"投宿设施名",
        "q3_20txt":"投宿数",
        "q3_21txt":"宿",
        "q4_1txt":"请问您本次旅行的目的是?(单选)",
        "q4_2txt":"商务",
        "q4_3txt":"观光",
        "q4_4txt":"探亲·访友",
        "q4_5txt":"购物",
        "q4_6txt":"参加活动",
        "q4_7txt":"欣赏戏剧·公演等",
        "q4_8txt":"餐饮",
        "q4_9txt":"其他",
        "q5_1txt":"包括您在内，请问本次旅行您和谁同行，共计几位游客? ※包括孩童和婴儿",
        "q5_2txt":"人（包括回答者）",
        "q5_3txt":"２人以上",
        "q5_4txt":"家人",
        "q5_5txt":"朋友",
        "q5_6txt":"公司、学校的集体旅行",
        "q5_7txt":"其他",
        "q6_1txt":"请问您是否知道本次旅游团全体成员（包括您）是第几次造访临海副都心呢？",
        "q6_2txt":"※总人数应与Q5一致。",
        "q6_3txt":"知道",
        "q6_4txt":"<span class=\"spn_ch_t_fs\">第一次造访此地的人数</span>",
        "q6_5txt":"<span class=\"spn_ch_t_fs\">人、</span>",
        "q6_6txt":"<span class=\"spn_ch_t_fs\">第二次造访此地的人数</span>",
        "q6_7txt":"<span class=\"spn_ch_t_fs\">人</span>",
        "q6_8txt":"<span class=\"spn_ch_t_fs\">第三次造访此地的人数</span>",
        "q6_9txt":"<span class=\"spn_ch_t_fs\">人、</span>",
        "q6_10txt":"<span class=\"spn_ch_t_fs\">第四次以上造访此地的人数</span>",
        "q6_11txt":"<span class=\"spn_ch_t_fs\">人</span>",
        "q6_12txt":"不知道",
        "q7_1_1txt":"请问这次是利用什么交通工具来到临海副都心内？",
        "q7_1_2txt":"临海线",
        "q7_1_3txt":"轻轨（百合鸥号）",
        "q7_1_4txt":"包车·观光巴士",
        "q7_1_5txt":"高速巴士",
        "q7_1_6txt":"公共巴士",
        "q7_1_7txt":"免费巡回巴士BAY SHUTTLE",
        "q7_1_8txt":"设施的接送巴士",
        "q7_1_9txt":"水上巴士",
        "q7_1_10txt":"出租车",
        "q7_1_11txt":"自驾车",
        "q7_1_12txt":"自行车",
        "q7_1_13txt":"出租自行车",
        "q7_1_14txt":"摩托车",
        "q7_1_15txt":"徒步",
        "q7_1_16txt":"其他",
        "q7_2_1txt":"这次旅行有去临海副都心的哪些景点呢？包括接下来计划要去的地方，请按造访时间的 顺序填入景点编号。同时也请填入使用的交通工具。",
        "q7_2_2txt":"到临海副都心内来的到达点<br>（车站，公交站等）",
        "q7_2_3txt":"景点<br>编号",
        "q7_2_4txt":"调查地点",
        "q7_2_5txt":"离开临海副都心时的出发点<br>（车站，公交站等）",
        "q7_2_6txt":"交通工具",
        "q7_2_7txt":"1 东京松下中心",
        "q7_2_8txt":"2 东京都水之科学馆",
        "q7_2_9txt":"3 有明竞技场",
        "q7_2_10txt":"4 东京时尚城 WANZA有明湾购物中心",
        "q7_2_11txt":"5 东京国际展示场",
        "q7_2_12txt":"6 东京都彩虹下水道博物馆",
        "q7_2_13txt":"7 TOC有明",
        "q7_2_14txt":"8 Differ有明",
        "q7_2_15txt":"9 东京临海广域防灾公园",
        "q7_2_16txt":"10 DiverCity东京购物中心",
        "q7_2_17txt":"11 东京港馆",
        "q7_2_18txt":"12 电信中心展望台",
        "q7_2_19txt":"13 调色板城",
        "q7_2_20txt":"14 大江户温泉物语",
        "q7_2_21txt":"15 MEGAWEB汽车主题公园",
        "q7_2_22txt":"16 Zepp东京",
        "q7_2_23txt":"17 日本科学未来馆",
        "q7_2_24txt":"18 THE GUNDAM BASE TOKYO",
        "q7_2_25txt":"19 Zepp DiverCity",
        "q7_2_26txt":"20 富士电视台本社大楼",
        "q7_2_27txt":"21 台场海滨公园",
        "q7_2_28txt":"22 东京JOYPOLIS",
        "q7_2_29txt":"23 AQUA CITY台场",
        "q7_2_30txt":"24 其他(请填写具体景点名称。)",
        "q7_2_31txt":"【附表】景点",
        "q7_2_32txt":"编号",
        "q7_2_33txt":"景点",
        "q7_2_34txt":"东京松下中心",
        "q7_2_35txt":"东京都水之科学馆",
        "q7_2_36txt":"有明竞技场",
        "q7_2_37txt":"东京时尚城 WANZA有明湾购物中心",
        "q7_2_38txt":"东京国际展示场",
        "q7_2_39txt":"东京都彩虹下水道博物馆",
        "q7_2_40txt":"TOC有明",
        "q7_2_41txt":"Differ有明",
        "q7_2_42txt":"东京临海广域防灾公园",
        "q7_2_43txt":"DiverCity东京购物中心",
        "q7_2_44txt":"东京港馆",
        "q7_2_45txt":"电信中心展望台",
        "q7_2_46txt":"调色板城",
        "q7_2_47txt":"大江户温泉物语",
        "q7_2_48txt":"MEGAWEB汽车主题公园",
        "q7_2_49txt":"编号",
        "q7_2_50txt":"景点",
        "q7_2_51txt":"Zepp东京",
        "q7_2_52txt":"日本科学未来馆",
        "q7_2_53txt":"THE GUNDAM BASE TOKYO",
        "q7_2_54txt":"Zepp DiverCity",
        "q7_2_55txt":"富士电视台本社大楼",
        "q7_2_56txt":"台场海滨公园",
        "q7_2_57txt":"东京JOYPOLIS",
        "q7_2_58txt":"AQUA CITY台场",
        "q7_2_59txt":"其他(请填写具体景点名称。)",
        "q7_2_60txt":"【附表】交通工具",
        "q7_2_61txt":"① 临海线",
        "q7_2_62txt":"② 轻轨（百合鸥号）",
        "q7_2_63txt":"③ 包车·观光巴士",
        "q7_2_64txt":"④ 高速巴士",
        "q7_2_65txt":"⑤ 公共巴士",
        "q7_2_66txt":"⑥ 免费巡回巴士BAY SHUTTLE",
        "q7_2_67txt":"⑦ 设施的接送巴士",
        "q7_2_68txt":"⑧ 水上巴士",
        "q7_2_69txt":"⑨ 出租车",
        "q7_2_70txt":"⑩ 自驾车",
        "q7_2_71txt":"⑪ 自行车",
        "q7_2_72txt":"⑫ 出租自行车",
        "q7_2_73txt":"⑬ 摩托车",
        "q7_2_74txt":"⑭ 徒步",
        "q7_2_75txt":"⑮ 其他",
        "q8_1txt":"请问此次造访临海副都心是否有包含在您参加的旅游团行程中呢？",
        "q8_2txt":"有包含",
        "q8_3txt":"没有包含",
        "q9_1txt":"您本次旅游中、有关临海副都心的信息是怎样得到的？（请复选）",
        "q9_2txt":"导游手册",
        "q9_3txt":"旅游专业杂志",
        "q9_4txt":"旅游宣传单",
        "q9_5txt":"报纸、新闻",
        "q9_6txt":"电视·广播",
        "q9_7txt":"亲友的对话",
        "q9_8txt":"旅行社",
        "q9_9txt":"旅游问询处",
        "q9_10txt":"互联网（电脑联网）",
        "q9_11txt":"互联网(手机上网)",
        "q9_12txt":"社交网络（脸书/推特/人人网等）",
        "q9_13txt":"其他",
        "q10_1txt":"您认为临海副都心如果有以下的什么设施等，会让您觉得更有吸引力呢？<span class=\"spn_u\">※可多选</span>",
        "q10_2txt":"【街景】",
        "q10_3txt":"欣赏自然风景",
        "q10_4txt":"欣赏现代化街道",
        "q10_5txt":"逛时尚街区",
        "q10_6txt":"【设施等】",
        "q10_7txt":"商业设施",
        "q10_8txt":"娱乐设施（游乐园等）",
        "q10_9txt":"学习设施（科学馆等）",
        "q10_10txt":"艺术设施（美术馆等）",
        "q10_11txt":"住宿设施（高级酒店等）",
        "q10_12txt":"餐饮设施",
        "q10_13txt":"体验型旅游设施（试穿和服等）",
        "q10_14txt":"运动设施",
        "q10_15txt":"灯饰活动",
        "q10_16txt":"水上活动景点",
        "q10_17txt":"文化娱乐活动",
        "q10_18txt":"眺望台",
        "q10_2_1txt":"关于您从“设施等”中选出的选项，请问您认为具体有什么样的内容，会让临海副都心变得更有吸引力呢？　请您具体填写",
        "q10_2_2txt":"",
        "q11_1txt":"请给出您对本次临海副都心之行的总体满意度。（单选）",
        "q11_2txt":"非常满意",
        "q11_3txt":"满意",
        "q11_4txt":"基本满意",
        "q11_5txt":"一般",
        "q11_6txt":"有点不满意",
        "q11_7txt":"不满意",
        "q11_8txt":"非常不满意",
        "q12_1txt":"您今后还想再来临海副都心旅行吗？（单选）",
        "q12_2txt":"一定来",
        "q12_3txt":"想来",
        "q12_4txt":"有点想来",
        "q12_5txt":"说不好",
        "q12_6txt":"不太想来",
        "q12_7txt":"不想来",
        "q12_8txt":"绝不再来",
        "q13_1txt":"此次造访临海副都心，您是否有感到不够满意或希望改善的地方呢？<span class=\"spn_u\">※可多选</span>",
        "q13_2txt":"太拥挤，无法好好地购物。",
        "q13_3txt":"前往各目的地的交通非常不方便。",
        "q13_4txt":"导览标志不够具体，难以找到目的地。",
        "q13_5txt":"外语（多国语言）的导览资料、标示牌不够充分。",
        "q13_6txt":"外语（多国语言）沟通困难。",
        "q13_7txt":"设施使用费用及门票等较贵。",
        "q13_8txt":"总体上，物价比较贵。",
        "q13_9txt":"餐厅等餐饮设施很拥挤，无法好好地享用餐点。",
        "q13_10txt":"能使用Wi-Fi的地方很少。",
        "q13_11txt":"可供休息的场所太少。",
        "q13_12txt":"不易获得周边地区信息。",
        "q13_13txt":"对治安状况感到不安。",
        "q13_14txt":"没有",
        "q13_15txt":"其他（如果还有其他您觉得比较在意的地方，不管是什么都行，请填写到下面的空格里。）",
        "end_txt":"本次问卷调查结束。非常感谢您的合作。"
		}

	]
}
